# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e39d6fb8a8b1a45a5ef4855fd158d1e1fac698df6c8c207c354af57d34e2308c2cebe317fb6e4cc8ae872b7618e08cef6a214a73c32d40f71026047bcdf028f6

test:
  secret_key_base: 40bfc9e2d4ecbfbae622e04d05f5d6728669ec1df79255e5e4426adc2368877e57bbd4b9f6d8f4fbd024e2545fe3f317ff447b898401dd1e1424afe56e67fd80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
